### ISSUE TITLE
Usability: hint for format of roster file (class creation)

### ISSUE THREAD

**Issue by neloe** [gopi1506/GDP_Team05#1]
I have no idea based on your UI what the roster input file for a class roster should look like; there is no hint

**Comment by vinaylinginedi** [comment]
The input text file should contain data as (i.e., Sumeet,s654826@nwmissouri.edu) name and mail Id which is separated by comma as delimiter. We will provide the hint with an example on the UI as well.

**Comment by gopi1506** [comment]
Tooltips have been implemented in our application at the time every file upload.
