### ISSUE TITLE
Dependence on Google Maps?

### ISSUE THREAD

**Issue by neloe** [gopi1506/GDP_Team05#2]
Your code keeps throwing JS errors where it's saying that the google maps API key is wrong.  Why are you using google maps?

![image](https://user-images.githubusercontent.com/278757/68488870-996a5580-020b-11ea-9655-1aef63553302.png)

**Comment by gopi1506** [comment]
It's a bootstrap error, Google maps functionality comes along with the bootstrap 4 its showing error because we did not include our API key.
This error won't affect any functionality in the application this is an independent error of bootstrap 4.

**Comment by gopi1506** [comment]
This error is not appearing anymore and not effecting our application.
