### ISSUE TITLE
Usability: Create Course

### ISSUE THREAD

**Issue by neloe** [gopi1506/GDP_Team05#3]
Add course has following usability issues:
* no format checking of URL for start/end links
* What is the paper clip button? Unclear indicators

**Comment by vinaylinginedi** [comment]
Above mentioned validation for start/end links are yet to be implemented. 
Regarding the paper clip button on UI is placed to serve the same functionality that we are providing thru button "choose file" once we change that functionality to paper clip button from "choose file" button we will remove the choose file button to make it clear for end user

**Comment by gopi1506** [comment]
Paper clips have been removed and the format is now correct with the survey links.
