### ISSUE TITLE
Usability: use of popups

### ISSUE THREAD

**Issue by neloe** [gopi1506/GDP_Team05#5]
Popups block input to rest of page; don't use a popup to tell me that I was successful at creating a codeword set and *require* me to acknowledge it before I can continue using the system

**Comment by gopi1506** [comment]
We are going to resolve these small changes like email verification, popups in the last after achieving the admin approval which is only left by now.

**Comment by gopi1506** [comment]
These pop-ups have been fixed for appropriate use now.
