### ISSUE TITLE
Missing Functionality: codeword sets?

### ISSUE THREAD

**Issue by neloe** [gopi1506/GDP_Team05#6]
Pulblish and edit codeword sets buttons don't seem to accomplish anything.  Delete works, though.  Unsure if this is lack of feedback or missing functionality.

**Comment by gopi1506** [comment]
We have functionality for Edit and publish ready but we don't want to enable till the lat to avoid the conflicts.

**Comment by neloe** [comment]
Not being enabled is the same as missing functionality; I would hesitate to close issues without having a resolution (either fixed, or will not fix)

**Comment by gopi1506** [comment]
Okay Dr.Eloe, I am gonna keep this open until I push the code for edit and publish.

**Comment by gopi1506** [comment]
Edit and publish buttons on the codeword set page are functional now.
