### ISSUE TITLE
Broken Functionality: Create Classes

### ISSUE THREAD

**Issue by neloe** [gopi1506/GDP_Team05#7]
I cannot select a codeword set while creating classes.  The list is not populated with any of the existing sets

**Comment by gopi1506** [comment]
This is fixed now and you can select a codeword set while creating a class.

**Comment by gopi1506** [comment]
![image](https://user-images.githubusercontent.com/43010422/69207579-ea385300-0b15-11ea-92d8-9703999d9dfb.png)
